# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "signature",
    srcs = [
        "RsaEntrySigner.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//java/com/google/tledger/domain/model",
        "//java/com/google/tledger/domain/ports",
        "@com_google_protobuf//java/util",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:jakarta_inject_jakarta_inject_api",
        "@pcit_mbs//java/com/google/mbs:certmanagement",
    ],
)
