module(name = "tledger")

bazel_dep(name = "rules_jvm_external", version = "6.9")
bazel_dep(name = "rules_java", version = "8.16.1")
bazel_dep(name = "grpc-java", version = "1.71.0", repo_name = "io_grpc_grpc_java")
bazel_dep(name = "grpc-proto", version = "0.0.0-20240627-ec30f58", repo_name = "io_grpc_grpc_proto")
bazel_dep(name = "protobuf", version = "32.1", repo_name = "com_google_protobuf")
bazel_dep(name = "rules_go", version = "0.52.0")
bazel_dep(name = "rules_proto", version = "7.1.0")
bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "rules_pkg", version = "1.1.0")
bazel_dep(name = "rules_cc", version = "0.2.8")
bazel_dep(name = "googleapis", version = "0.0.0-20251211-05f65958")
bazel_dep(name = "rpmpack", version = "0.6.0", repo_name = "com_github_google_rpmpack")
bazel_dep(name = "rules_aws", version = "0.0.0")
local_path_override(
    module_name = "rules_aws",
    path = "container-tools",
)

bazel_dep(name = "pcit_api", version = "0.0.0")
local_path_override(
    module_name = "pcit_api",
    path = "api",
)

bazel_dep(name = "pcit_mbs", version = "0.0.0")
local_path_override(
    module_name = "pcit_mbs",
    path = "mbs",
)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "confidential-federated-compute",
    build_file_content = """
filegroup(
  name = "sysroot",
  srcs = glob(["*/**"]),
  visibility = ["//visibility:public"],
)
""",
    urls = ["file:third_party/sysroot.tar.xz"],
)

bazel_dep(name = "toolchains_llvm", version = "1.4.0")

llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    name = "cpp_toolchain",
    llvm_version = "20.1.0",
)
llvm.sysroot(
    name = "cpp_toolchain",
    label = "@confidential-federated-compute//:sysroot",
    targets = ["linux-x86_64"],
)
use_repo(llvm, "cpp_toolchain")

register_toolchains("@cpp_toolchain//:all")

bazel_dep(name = "rules_boost", repo_name = "com_github_nelhage_rules_boost")
archive_override(
    module_name = "rules_boost",
    integrity = "sha256-ZLcmvYKc2FqgLvR96ApPXxp8+sXKqhBlCK66PY/uFIo=",
    strip_prefix = "rules_boost-e3adfd8d6733c914d2b91a65fb7175af09602281",
    urls = ["https://github.com/nelhage/rules_boost/archive/e3adfd8d6733c914d2b91a65fb7175af09602281.tar.gz"],
)

archive_override(
    module_name = "oak",
    sha256 = "96f8c60c00f87e905141e1cd12ccee53ec1028b7a52b9969b7bac833efd0e58f",
    strip_prefix = "oak-125200702f216cf02ac218fe6737f44cd001c803",
    url = "https://github.com/project-oak/oak/archive/125200702f216cf02ac218fe6737f44cd001c803.tar.gz",
)

single_version_override(
    module_name = "rules_oci",
    version = "1.8.0",
)

single_version_override(
    module_name = "grpc",
    version = "1.69.0",
)

http_archive(
    name = "google-cloud-sdk",
    build_file_content = """
package(default_visibility = ["//visibility:public"])
exports_files(["google-cloud-sdk"])
""",
    # latest from https://cloud.google.com/storage/docs/gsutil_install#linux as of 2021-12-16
    sha256 = "94328b9c6559a1b7ec2eeaab9ef0e4702215e16e8327c5b99718750526ae1efe",
    url = "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-367.0.0-linux-x86_64.tar.gz",
)

# Version updated on 2025-05-28
COORDINATOR_VERSION = "v1.24.0-rc01"

COORDINATOR_COMMIT_HASH = "0e6d1584199a6f9cda271dd29beb7031d9af2b64"

AWS_SDK_VERSION = "2.21.17"

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.artifact(
    testonly = True,
    artifact = "testcontainers",
    group = "org.testcontainers",
    version = "1.21.4",
)
maven.artifact(
    testonly = True,
    artifact = "localstack",
    group = "org.testcontainers",
    version = "1.21.4",
)
maven.artifact(
    testonly = False,
    artifact = "junit",
    group = "junit",
    version = "4.13.2",
)
maven.install(
    artifacts = [
        "com.google.guava:guava:33.5.0-jre",
        "com.google.inject:guice:7.0.0",
        "com.google.flogger:flogger:0.9",
        "com.google.flogger:flogger-system-backend:0.9",
        "junit:junit:4.13.2",
        "com.google.truth:truth:1.4.5",
        "org.mockito:mockito-core:3.12.4",
        "com.beust:jcommander:1.82",
        "com.google.protobuf:protobuf-java:4.29.3",
        "io.grpc:grpc-protobuf:1.71.0",
        "io.grpc:grpc-services:1.71.0",
        "com.google.api.grpc:proto-google-common-protos:2.51.0",
        "jakarta.inject:jakarta.inject-api:2.0.1",
        "io.grpc:grpc-netty-shaded:1.71.0",
        "com.google.auth:google-auth-library-oauth2-http:1.31.0",
        "software.amazon.awssdk:s3:" + AWS_SDK_VERSION,
        "software.amazon.awssdk:imds:" + AWS_SDK_VERSION,
        "com.google.code.gson:gson:2.11.0",
        "software.amazon.awssdk:regions:" + AWS_SDK_VERSION,
        "software.amazon.awssdk:auth:" + AWS_SDK_VERSION,
        "software.amazon.awssdk:url-connection-client:" + AWS_SDK_VERSION,
        "org.testcontainers:testcontainers:1.21.4",
        "org.testcontainers:localstack:1.21.4",
        "com.linecorp.armeria:armeria:1.34.1",
        "com.linecorp.armeria:armeria-grpc:1.34.1",
        "org.slf4j:slf4j-jdk14:2.0.16",
        "ch.qos.logback:logback-classic:1.5.6",
        "ch.qos.logback:logback-core:1.5.6",
        "com.google.flogger:flogger-slf4j-backend:0.9",
        "net.logstash.logback:logstash-logback-encoder:7.4",
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
use_repo(maven, "maven")
