# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

package(default_visibility = ["//visibility:public"])

string_flag(
    name = "crowdstrike_cid",
    build_setting_default = "",
)

string_flag(
    name = "crowdstrike_bucket",
    build_setting_default = "",
)

string_flag(
    name = "crowdstrike_key",
    build_setting_default = "",
)

string_flag(
    name = "crowdstrike_sha256",
    build_setting_default = "",
)

string_flag(
    name = "pcit_packer_iam_instance_profile",
    build_setting_default = "",
)
